-- 创建分布式锁表结构
CREATE TABLE IF NOT EXISTS LOCK
(
    -- 主键自增ID
    ID              INTEGER NOT NULL CONSTRAINT LOCK_PK PRIMARY KEY AUTOINCREMENT CONSTRAINT LOCK_U1 UNIQUE,
    -- 锁唯一名称
    LOCK_NAME       TEXT    NOT NULL CONSTRAINT LOCK_U2 UNIQUE,
    -- 锁创建时间
    CREATED_TIME    TEXT    NOT NULL,
    -- 锁超时时间
    EXPIRED_TIME    TEXT    NOT NULL
);