--创建消息队列表结构
CREATE TABLE IF NOT EXISTS QUEUE
(
    -- 主键自增ID
    ID              INTEGER NOT NULL CONSTRAINT QUEUE_PK PRIMARY KEY AUTOINCREMENT CONSTRAINT QUEUE_U1 UNIQUE,
    -- 消息内容
    MESSAGE_CONTENT TEXT    NOT NULL,
    -- 生产时间
    PRODUCED_TIME   TEXT    NOT NULL
);